gearman/gearmand

libgearman-server/plugins/protocol/http/protocol.cc

[LP](http://bazaar.launchpad.net/~1-infe-w/gearmand/1.0/revision/802)
debian Bug#774143: Acknowledgement 
> Package: gearman-job-server
Version: 1.0.6-4
Status: install ok installed
Installed-Size: 268
Architecture: amd64
Severity: serious
> A bad HTTP request force gearmand (>=0.33 AFAIK) to run in in endless loop until memory out. See bug report https://bugs.launchpad.net/gearmand/+bug/1348865

malicious HTTP request kills gearmand

---

libgearman-server/plugins/protocol/http/protocol.cc

Debian Bug #774144: Acknowledgement
> there is a bug in HTTP plugin implementation: gearmand doesn't return
worker result to the client HTTP response as expected. See bug report
https://bugs.launchpad.net/gearmand/+bug/1152707

NO worker result in HTTP-response content

---

version.m4

This ties tags to commits that build them rather than requiring an extra
commit to make a release.

Use git describe to determine version

---

ChangeLog
Makefile.am
configure.ac
m4/ax_generate_changelog.m4

We don't need to hand-roll this, as we've already recorded this in the
git changelog.

Generate ChangeLog in make dist

---

.travis.yml

this pr aims to run travis ci build with different compiler versions:
- gcc-4.9, g++-4.9
- gcc-5, g++-5

travis ci build matrix with different compilers

---

tests/libgearman-1.0/fork.cc

Been doing some analysis. So what happens is this:
1) child forks, which ends up with the same socket for both child and parent.
1-parent) parent calls waitpid to wait for child to exit
2) child successfully echoes
3) child calls exit() which calls some registered atexit handler which
shuts down the shared connection
4) parent wakes up, sees client was successful, tries to use the same
connection socket which was just shut down.
I don't know how this test worked ever. But most likely there was a race
between the SIGCHLD and the exit handlers, and that may have been fixed
in recent libc's.
Closes #44

Use _exit() in fork test to fix race

---

PROTOCOL
bin/gearadmin.cc
docs/source/bin/gearadmin.rst
docs/source/protocol/text.rst
libgearman-server/text.cc
tests/cli.cc

This PL is done with regard to the [issue 37](https://github.com/gearman/gearmand/issues/37).

remove gearmand text command shutdown

---

libgearman/client.cc

This fixes a compilation error with GCC 7, because you can't compare a pointer and a bool in C++14.

Fix comparison of pointer and bool

---

docs/source/license.rst

After getting the copyright holder Brian Aker's approval, we
are updating thise license to a license that is compatible with
Debian so that the docs can be included. Please see comments in
https://github.com/gearman/gearmand/issues/11#issuecomment-249449893
for confirmation.
Closes #11

Change docs license to CC-BY-SA 4.0

---

tests/include.am

Exclude unreliable `t/cycle` from `make test`, but let the possibility to run it via `make test-cycle`.
See also [PR90](https://github.com/gearman/gearmand/pull/90]

exclude unreliable cycle test

---

libgearman-server/plugins/protocol/http/protocol.cc

Issue #98 describs misbehavior. This PR should fix it.

gearmand should release http client if request contains 'X-Gearman-Background: true' header

---

libgearman-server/log.cc

switching from UTC logging timestamp to `localtime`.
Issue #123

logging time

---

libgearman-server/plugins/protocol/http/protocol.cc

libgearman-server/plugins/http/protocol:unpack
refer to line 542:
if ((ret_ptr= gearmand_packet_create(packet, unique, unique_size +1)) != GEARMAND_SUCCESS)

http protocol unpack: default unique_size should be 1 instead of 2

---

bootstrap.sh

It was forgotten to add that shortopt so even if the help said you could specify the options for the configure phase, it was not true.
Calling ./bootstrap.sh -c -o "--prefix=my/dir" would print "error - unrecognized option -o"

Added configure options to bootstrap.sh arguments

---

bootstrap.sh

Boostrap.sh Doesn't recognize openSUSE Tubleweed because it has name 'opensuse-tumbleweed' not just 'opensuse' as it expects.

Boostrap.sh can't handle openSUSE Tumbleweed

---

Makefile.am
support/gearmand.spec.in

Tarball didn't add README.md so this one fixes that also add it back to gearmand.spec.in.

Add README.md to Makefile.am EXTRA_DIST and to gearmand.spec.in file

---

libtest/thread.hpp

As current code throws warning about thread condition handling in current implementation this @p-alik small patch fixes those

Fix GCC 8 thread handling and abort warnings

---

libgearman-server/log.cc

This one fixes one fall through warning in log.cc which compiler picks up separated from PR #114

Fix fallthrough warning in log.cc

---

libgearman-server/gearmand.cc

This is pragmatic way of solving problem: 
```libgearman-server/gearmand.cc: In function ‘gearmand_error_t 
gearmand_port_add(gearmand_st*, const char*, gearmand_error_t (*)(gearman_server_con_st*), gearmand_error_t (*)(gearman_server_con_st*))’:
libgearman-server/gearmand.cc:325:10: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 32 equals destination size [-Werror=stringop-truncation]
strncpy(gearmand->_port_list.back().port, port, NI_MAXSERV);
```
Which is new GCC7/8 warning

Fix strncpy problem in libgearman-server/gearmand.cc

---

libtest/thread.hpp

needs to be redone as it fix:
libtest/thread.hpp:227:13: error: cast between incompatible function types from ‘void (*)(context_st*)’
to ‘libtest::thread::Thread::start_routine_fn’ {aka ‘void* (*)(void*)’} [-Werror=cast-function-type]

GCC8 tries to be more strict with type casting

---

.travis.yml
libgearman-server/io.cc
libgearman-server/log.cc
libgearman-server/server.cc
libgearman/connection.cc
libgearman/run.cc
libgearman/worker.cc
libhashkit/jenkins.cc
libhashkit/murmur3.cc
libtest/main.cc
tests/libgearman-1.0/worker_test.cc
util/instance.cc

In GCC 7+ some `-W` flags were added or changed their behavior and is causing the build to fail. This PR takes the somewhat lazy route of turning these errors into warnings instead to let it compile.
Tested on Ubuntu 18.04 with GCC 7.3.0, and on Travis here: https://travis-ci.com/defect/gearmand/builds/90657856

Turn new GCC 7 errors to warnings

---

libgearman-server/plugins/queue/libmemcached/queue.cc
libgearman-server/plugins/queue/redis/queue.cc
libgearman-server/plugins/queue/redis/queue.h
tests/memcached_test.cc
tests/redis.cc

Hey folks! I implemented a `--libmemcached-prefix` flag for some experiments we're doing at work. It allows you overrides the default `gear_` prefix used in the memcached key so that more than one gearmand instance can use the same memcached without replaying each others jobs. I also saw https://github.com/gearman/gearmand/issues/60 for the same thing in the redis plugin and thought I'd take a stab at that too since the principle is the same.
I know using the persistence plugins isn't recommended (as @SpamapS noted in the issue above), but thought I'd might as well see if anyone was interested in a patch. If omitted, the new parameters default to the current `gear_` (libmemcached) and `_gear_` (redis) prefixes.

Support for key prefix in redis and libmemcached queue plugins

---

libgearman-server/timer.cc

cherry picked from #114 to solve:
```
Viva64-EM
full
66
/nfs/home/dmka/src/gearmand/libgearman-server/timer.cc
error
V512
A call of the 'memset' function will lead to underflow of the buffer 'fds'.
false
1
{
memset(fds, 0, sizeof(pollfd));
fds[0].fd= -1; //STDIN_FILENO;
------------
```
https://github.com/p-alik/gearmand/issues/8

memset bug fixing in current_epoch_handler

---

libgearman-server/plugins/queue/mysql/queue.cc

MySQL 8.0.1 and 8.0.3+ do not define a 'my_bool' type.
Refer to issue #165 and https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html.

Issue 165: Fix unknown type name 'my_bool' when compiling with MySQL 8+

---

libgearman/connection.hpp
libgearman/interface/error.hpp
libgearman/interface/packet.hpp
libgearman/interface/universal.hpp
libgearman/packet.cc
libgearman/server_options.cc
libgearman/server_options.hpp
libgearman/vector.hpp

based on ` git diff pvs-analyze master -- libgearman`

libgearman part of #114 Pvs analyze 

---

gearmand/gearmand.cc

Fix rpmlint 'missing-call-to-setgroups-before-setuid' error

---

.travis.yml
libgearman-server/io.cc
libtest/client.cc

* Change Travis CI builds to configure with '--enable-ssl' for more complete code coverage.
* Add GCC pragmas to avoid compilation errors with -Wimplicit-fallthrough on gcc 7/8.

Fix gcc 7/8 compilation errors from -Wimplicit-fallthrough with SSL support enabled

---

libgearman-server/gearmand_thread.cc
libgearman-server/struct/gearmand.h
libgearman-server/struct/packet.h
libgearman-server/struct/thread.h
tests/libgearman-1.0/regression.cc

cherry-picking from #114 Pvs analyze part 2

---

libgearman-server/plugins/queue/redis/queue.cc

Fixes bug discussed in https://github.com/gearman/gearmand/issues/216

fixed bug which prevents whitespace in the job unique id

---

libgearman-server/gearmand_thread.cc
libgearman-server/plugins/protocol/http/protocol.cc
libgearman-server/plugins/queue/sqlite/queue.cc
libgearman-server/struct/io.h
libgearman-server/struct/port.h
libgearman-server/struct/server.h

last part of commits cherry-picked from #114

Pvs analyze part3

---

.travis.yml

This should make it more obvious which version of the compiler each build is using. This syntax works with both clang and gcc.

Add explicit '${CC} --version' to Travis CI builds

---

libgearman-server/io.cc
libgearman-server/server.cc
libgearman/connection.cc
libgearman/run.cc
libgearman/worker.cc
libhashkit/jenkins.cc
libhashkit/murmur3.cc
libtest/client.cc
util/instance.cc

As mentioned in PR #193 there is several fall through warnings that needs to be addressed and fixed

Add /* fall-thru */ to get rid of compiling fall through warnings

---

docs/source/gearmand.rst

This doesn't work as an increment. It only works if you pass in the
right level. Whether that is right or not is less important than
matching the docs to how the program actually works right now.
Closes: https://bugs.launchpad.net/ubuntu/+source/gearmand/+bug/1357523

Fix manpage/docs for gearmand --verbose level

---

libgearman-server/io.cc

An incorrect number of arguments were being passed to `gearman_log_info()` based on the specified format string. This fixes that, addressing issue #235.

Fixed bug in SSL error logging (Issue #235)

---

.travis.yml

This PR addresses issue #238. It also adds builds using clang 7 and clang 8.
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment says:
> Since Ubuntu 14.04 reaches End of Life on April 30th, 2019, we’ll be gradually setting the default distribution for builds to Linux, Ubuntu Xenial 16.04.

Update Travis CI to Ubuntu Xenial and add Clang 7 and 8 builds (Issue #238)

---

libtest/socket.cc

This splits off one of the changes from PR #229 into a separate PR.
It fixes the following warning message when compiled with gcc 8.2.0+:
```
libtest/socket.cc:58:12: warning: ‘char* strncpy(char*, const char*, size_t)’
output truncated before terminating nul copying as many bytes from a
string as its length [-Wstringop-truncation]
strncpy(global_socket, socket, strlen(socket));
```
More information:
https://developers.redhat.com/blog/2018/05/24/detecting-string-truncation-with-gcc-8/
Relevant section:
> *Mitigating strncpy Truncation*
>
> Since it is not possible to avoid truncation by strncpy, when using other functions is not feasible, it is necessary to make sure the result of strncpy is properly NUL-terminated and the NUL must be inserted explicitly, after strncpy has returned:
```C …
```

Fix strncpy() warning in libtest/socket.cc when compiling with gcc 8

---

libgearman/run.cc

This splits off one of the changes from PR #229 into a separate PR.
It fixes the following warning message when compiled with gcc 8.2.0+:
```
libgearman/run.cc:272:16: warning: ‘char* strncpy(char*, const char*, size_t)’
specified bound 64 equals destination size [-Wstringop-truncation]
strncpy(task->unique, task->recv->arg[0], GEARMAN_MAX_UNIQUE_SIZE);
```
More information:
https://developers.redhat.com/blog/2018/05/24/detecting-string-truncation-with-gcc-8/
Relevant section:
> *Mitigating strncpy Truncation*
>
> Since it is not possible to avoid truncation by strncpy, when using other functions is not feasible, it is necessary to make sure the result of strncpy is properly NUL-terminated and the NUL must be inserted explicitly, after strncpy has returned:
```C
char pathname[256]; …
```

Fix strncpy() warning in libgearman/run.cc when compiling with gcc 8

---

PROTOCOL
libgearman-server/connection.cc

This addresses issue #196 by fixing the conversion of the timeout in milliseconds to the `struct timeval` in `libgearman-server/connection.cc`. This seems the simplest way to fix this rather egregious bug. I still think seconds is the more intuitive unit for a job timeout, but that would require more widespread changes and I haven't received much feedback preferring that as a solution.
Any objection to my modification of the PROTOCOL file to firmly document that the timeout should be specified in milliseconds?

Address Issue #196 by fixing the conversion of milliseconds to timeval

---

bootstrap.sh

Scientific Linux (SL) is a Linux distribution produced by Fermilab, CERN, DESY, and ETH Zurich and utilized by various other academic and US government institutions. It is a free and open-source alternative distribution that is based on RHEL (and also CentOS). Its packages, kernels, and executables are identical to RHEL/CentOS.
The only problem is `/etc/redhat-release` is different and the `awk` command in `bootstrap.sh` uses the wrong field when parsing the version number with `awk`. This PR fixes that.

Add support for Scientific Linux (free alternative to RHEL/CentOS)

---

.travis.yml
libgearman-server/gearmand_thread.cc
libgearman/server_options.cc

Alternative patch to PR#247.
This one retains the new initializer brace syntax for newer versions of gcc. Primarily for compatibility with RHEL/CentOS 7.x, it uses a preprocessor conditional to work around the lack of full brace initializer syntax in gcc 4.8.5.
This PR also adds gcc/g++ 4.8.5 builds to Travis CI.

Issue #246: Support gcc 4.8.5/CentOS 7.x

---

ChangeLog

Trivial change to ChangeLog to correct some spelling errors.

Fix misspellings in ChangeLog

---

libtest/has.cc

Change POSTGES_IS_RUNNING_AND_SETUP to POSTGRES_IS_RUNNING_AND_SETUP.

Correct POSTGRES misspelling

---

configure.ac
libgearman-server/gearmand.cc
libgearman-server/gearmand.h
libgearman-server/include.am
m4/ax_libevent.m4

gearmand depends on libevent2, it checked only for libevent. It used
libevent2 anyways but without initializing its thread support.
This should fix it.

fix initialization of libevent2 thread support

---

libtest/has.cc

strncpy() may not terminate the dest if it is smaller than the given
length.
This has been fixed to silence a compiler warning. It is just library
test code, nothing that could cause problems in gearman.

libtest: fix potential unterminated string

---

tests/libgearman-1.0/worker_test.cc

The PR solves the issue #260 and makes obsolete warning pragma
introduced in
585a04ec358449f9b6040ef1439993fe70bfa0cb

set proper paramters of snprintf to prevent truncation warnings

---

libgearman-1.0/client.h
libgearman-1.0/worker.h
libgearman-server/io.cc
libgearman-server/plugins/protocol/gear/protocol.cc
libgearman/client.cc
libgearman/connection.cc
libgearman/interface/universal.hpp
libgearman/universal.cc
libgearman/universal.hpp
libtest/client.cc
util/instance.cc

There seems to be renewed interest in SSL connections from PHP to gearmand (coming up twice in the past two weeks: today on Stack Overflow and recently over at wcgallego/pecl-gearman/issues/43), so I have rebased and tweaked the patch tracked at issue #63 in the hopes of landing this.
There were also some references to `wolfssl` and `CyaTLSv1_client_method` that I have corrected or made more generic. If you prefer that I split off those minor things into a separate PR, just let me know.
The original patch came from here:
http://bugs.launchpad.net/gearmand/+bug/1338861
But I have made a few tweaks.

Issue #63: Add set_ssl API to libgearman for PHP extension and other potential uses

---

.travis.yml

This PR adds gcc-9 (on Bionic) and clang-9 to the gearmand Travis CI configuration. The gcc-9 build currently fails with yet another `strncpy` truncation warning in `libtest/has.cc`. This was one wasn't noticed previously because it requires memcached and libmemcached for that code to be compiled. @zvpunry (or I) will submit a PR soon which fixes this. Once that is merged, the gcc-9 build in this PR will pass. (Tested here: https://travis-ci.org/esabol/gearmand/builds/635884516)

Add gcc-9 and clang-9 to Travis CI

---

.travis.yml

I noticed that under "View config" on Travis CI, it says:
```
root: deprecated key sudo (The key `sudo` has no effect anymore.)
```
I googled that and found this blog entry:
* https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
All the Python repos subsequently removed `sudo: required` from their `.travis.yml` files. For example: https://github.com/python/mypy/issues/6675
We might as well do the same!

.travis.yml: Removed deprecated sudo tag and changed the matrix tag to jobs

---

libtest/cmdline.h
tests/hostile.cc

If 'vec' is a vector, calling 'vec[0]' will crash the program if
'vec' is empty and '-Wp,-D_GLIBCXX_ASSERTIONS' given in CXXFLAGS.
Fixes https://github.com/gearman/gearmand/issues/272

Fix crashing of tests when '-Wp,-D_GLIBCXX_ASSERTIONS' is given

---

libtest/http.cc

This PR fixes the problems in `libtest/http.cc` when you compile with CXXFLAGS=-'-Wp,-D_GLIBCXX_ASSERTIONS' on Fedora 31. Refer to issue #278 (and issue #275).

Issue 278: Fix crashing in libtest/http.cc when '-Wp,-D_GLIBCXX_ASSERTIONS' is given

---

libtest/cmdline.cc

Hello,
I'm not sure about this fix. 
In the CPANTesters I noticed this error : 
```
libtest/cmdline.cc:65:15: error: 'environ' was declared 'extern' and later 'static' [-fpermissive]
65 | static char **environ= NULL;
|               ^~~~~~~
In file included from /usr/include/fortify/unistd.h:22,
from ./libtest/common.h:77,
from libtest/cmdline.cc:39:
/usr/include/unistd.h:183:15: note: previous declaration of 'environ'
183 | extern char **environ;
|               ^~~~~~~
```
From http://www.cpantesters.org/cpan/report/003e64ec-ca05-11ea-9066-e374b0ba08e8 (it is on an alpine Linux)
From the [git blame](https://github.com/gearman/gearmand/blame/master/libtest/cmdline.cc#L65) it was added for OSX. I have tested with and without #ifdef on my machine but I have not tested on OSX... 
Best …

Fix error: ‘environ’ was declared ‘extern’ and later ‘static’ [-fpermissive]

---

libtest/include.am

It should be "suppression", not "supression". :) I kept a misspelled "valgrind-supression" target for historical reasons. Would you rather it be removed entirely?

Fix misspellings of "suppression" in the Makefile

---

.travis.yml

I still couldn't figure out how to reopen PR #275, so I'm just going to open a new PR.
As discussed in issue #272, this PR ensures C++ STL is used properly, according to `_GLIBCXX_ASSERTIONS`. This only adds it to the gcc-9 build. Let me know if you think it should be added to other gcc/g++ builds.
Reference:
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html

Add CXXFLAGS=-Wp,-D_GLIBCXX_ASSERTIONS to the gcc-9 build in Travis CI (Redux)

---

docs/source/conf.py.in
docs/source/libgearman/gearman_log_fn.rst

Gearman log fn doc

---

libgearman-server/job.cc

For some reason this line was indented by two tabs instead of spaces like the other lines. And then there was another blank line with just two tabs on it.

Fix indentation/whitespace in libgearman-server/job.cc

---

libgearman-server/connection.cc

As mentioned in issue #291, this addresses the following compilation warning seen on at least some versions of macOS (neé Mac OS X):
```
libgearman-server/connection.cc:722:29: warning: implicit conversion loses integer precision: 'long' to
'__darwin_suseconds_t' (aka 'int') [-Wshorten-64-to-32]
timeout_tv.tv_usec= (long)((milliseconds % 1000) * 1000);
```
At least some versions of macOS, Apple apparently used `int` instead of `long` for `tv_usec` in `struct timeval`. The solution is to use `suseconds_t` for the type instead.
This works on Linux as well in my testing, but does anyone think this change should only be made on macOS? If so, I could make it this instead:
```C
#ifdef __APPLE__
timeout_tv.tv_usec= (suseconds_t)((milliseconds % 1000) * 1000);
#else
timeout_tv.tv_usec= …
```

Use suseconds_t instead of long

---

tests/vector.cc

This PR addresses issue #279 and fixes "make test" on 32-bit systems. Thanks to @cheese for his suggestion on how to do this.
`std::numeric_limits<type>` is defined in `<limits>`, but that's not explicitly included by `tests/vector.cc`. I presume one of the other `#include`s is pulling it in somehow, since the code compiles and tests cleanly, but maybe we should have an explicit `#include <limits>`? Let me know what you think.

Issue #279: Fix t/vector test on 32-bit systems

---

bootstrap.sh
libhashkit/common.h

This PR addresses issue #293 and adds support for bootstrapping on Alpine Linux.
I did some additional research into `__WORDSIZE`, and what I saw was a confusing mess, as usual whenever I seem to look into C preprocessor macros. I saw a lot of recommendations to use `__BITS_PER_LONG` or `BITS_PER_LONG` or `LONG_BITS` instead. Plus a whole host of other methods. I eventually came across this Alpine patch for libmemcached:
https://git.alpinelinux.org/aports/plain/main/libmemcached/musl-fixes.patch
That at least gave me confidence to add some checks for `LONG_BITS`. Should I add `__BITS_PER_LONG` or `BITS_PER_LONG` too? Am I overcomplicating this? Probably!
And I think you need to `#include <limits.h>`. I didn't see an `#include` for that, but maybe I missed it somewhere. Anyway, I added it, …

Issue #293: Bootstrap on Alpine

---

ChangeLog
bootstrap.sh

When I was young, I won my school's spelling bee 🥇 and competed at the state level of the National Spelling Bee, so I'm somewhat sensitive to spelling errors. 🙂

Fix misspellings of "occurred"

---

README.md

Add link to Clint’s public key for people who want to verify signed releases. This addresses issue #310.

Update README.md with link to key used to sign releases

---

libtest/cmdline.cc

This should improve compatibility with older versions of Alpine/MUSL that didn't define `POSIX_SPAWN_USEVFORK` but did define `__linux__`, obviously. With this change, `POSIX_SPAWN_USEVFORK` is only used if it is defined or if glibc is being used.
This change replicates [a similar change made to the same file in the libmemcached project](https://git.alpinelinux.org/aports/tree/main/libmemcached/musl-fixes.patch).

Issue #321: Improve compatibility with older versions of Alpine

---

libgearman-server/text.cc

This has never been correct, and has only ever shown 1 if there are any
in a priority, or 0 if there are not. That is because the next
struct field that as used is confusingly not maintained in this context.
Closes #337

Fix bug in prioritystatus

---

docs/source/bin/gearadmin.rst

The following were added:
```bash
--cancel-job
--show-unique-jobs
--show-jobs
--getpid
--priority-status
-S [ --ssl ]
```
Closes #317

Issue #317: MAN file for gearadmin was missing commands

---

libgearman-server/gearmand.cc

Credit for this goes to Andy B (Launchpad Id: u-launchpad-x) who submitted this patch to the gearmand Launchpad on 2014-05-14. The original Launchpad URL for this patch is https://bugs.launchpad.net/gearmand/+bug/1319250.
Andy B wrote:
> Steps to reproduce:
> 
> 1. start gearmand
> 2. on ipv6 localhost: gearadmin -h ::1 --workers
> 3. on ipv6 link-local: gearadmin -h fe80::a00:27ff:fe34:3379%eth0 --workers
>
> Actual output for 2:
> 33 ::e8bf:8995:757f:0%33 - :
> .
> Actual output for 3:
> 33 fe80::e8bf:444b:657f:0%33 - :
> .
>
> Expected output for 2:
> 33 ::1 - :
> .
> Expected output for 3:
> 33 fe80::a00:27ff:fe34:3379%eth0 - :
> .
>
> This is due to struct sockaddr not being big enough to hold struct sockaddr_in6. struct sockaddr_storage is supposed to be used for this. Attached …

Issue #304: Fix IPv6 addresses in gearadmin --workers and log output

---

libgearman-server/plugins/queue/postgres/queue.cc

when table name contains schema name like `foo.bar`, gearman can't find it in database because it uses query `SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME  = ...` and `TABLE_NAME` column data contains only `bar` part so each time on startup it tries to recreate it and on second start it fails `PQexec:ERROR:  relation "bar" already exists`
this is a quick fix, correct fix is to add non-default schema support but this way it will work at least
**COMPATIBILITY NOTE**: `IF NOT EXISTS` added in Postgres 9.1

Fix Postgres queue table creation on startup

---

docs/source/protocol/text.rst

```bash
[octavn@dev ~]$ gearadmin --priority-status
convert	0	0	0	25
.
[octavn@dev ~]$ telnet localhost 4730
Trying ::1...
Connected to localhost.
Escape character is '^]'.
prioritystatus
convert	0	0	0	25
.
```

prioritystatus was in gearmand binary but not in docs

---

docs/source/protocol/text.rst

proof: https://github.com/gearman/gearmand/blob/master/libgearman-server/text.cc#L363

Updated docs: The verbose text command only READS the verbose setting

---

libtest/dns.cc
tests/libgearman-1.0/client_test.cc
tests/libgearman-1.0/worker_test.cc

"make test" and the GitHub CI workflow currently fail because the `gearman.info` website no longer exists. This merge request replaces the tests using the gearman.info domain with google.com. This addresses issue #346.
Is it OK to use google.com? I thought so, but if you have a better replacement....
There's still one test that references `exist.gearman.info`, but it's skipped. I didn't change that one. Let me know if I should. Or maybe just remove this skipped test entirely?
Tag @SpamapS

Issue #346: Remove reliance on gearman.info website from tests

---

.github/workflows/c-cpp.yml
libgearman-server/gearmand.cc

This PR refines the GitHub Actions CI workflow to support a matrix of compiler versions. This is needed so that we can "retire" Travis CI.
I'd like to rename the `.github/workflow/c-cpp.yml` file to `ci.yml`, but I haven't done that yet. Let me know what you think about that.

Refine GitHub Actions CI workflow to support a matrix of compiler versions

---

.github/workflows/c-cpp.yml
Makefile.am
benchmark/benchmark.h
configure.ac
gearmand/gearmand.cc
gearmand/server_common.h
libboost/include.am
libgearman-server/common.h

This also enables a build target on Ubuntu 22.04 with the latest gcc version.
Tested to still work at least as far back as Ubuntu 16.04.
Closes #351

Update build files to work with more modern autotools

---

.github/workflows/c-cpp.yml

This trivial pull request partially addresses issue #354. It eliminates the following warnings currently emitted by the GitHub Actions CI workflow:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2
All it does is change `uses: actions/checkout@v2` to `uses: actions/checkout@v3`.

Updated actions/checkout to v3 in GitHub Actions CI workflow

---

libgearman-server/plugins/protocol/http/protocol.cc

In my testing on Alpine 3.13 (which has gcc 10.2.1) and 3.17 (which has gcc 12.2.1), the following warning was printed during the builds:
```
CXX      libgearman-server/plugins/protocol/http/libgearman_server_la-protocol.lo
libgearman-server/plugins/protocol/http/protocol.cc: In member function 'virtual size_t HTTPtext::pack(const gearmand_packet_st*, gearman_server_con_st*, void*, size_t, gearmand_error_t&)':
libgearman-server/plugins/protocol/http/protocol.cc:153:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
153 |       gearmand_log_debug(GEARMAN_DEFAULT_LOG_PARAM,
|       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
154 |                          "Bad packet command: gearmand_command_t:%s",
| …
```

Silence implicit fallthrough warning on newer GCC versions

---

.github/workflows/c-cpp.yml

This pull request partially addresses issue #354 by restoring `CXXFLAGS="-Wp,-D_GLIBCXX_ASSERTIONS"` to the gcc-9 and higher builds in GitHub Actions CI. This was previously in the Travis CI, but I forgot to include it in the transition to GitHub Action CI. The gcc documentation says that it "enables extra error checking in the form of precondition assertions, such as bounds checking in strings and null pointer checks when dereferencing smart pointers." This was useful in finding multiple errors in the gearmand source code in the past.

Added CXXFLAGS="-Wp,-D_GLIBCXX_ASSERTIONS" to gcc-9 and higher builds in GitHub Actions CI

---

m4/ax_libmemcached.m4

`libmemcachedutil` depends on `libmemcached`, and as such it should be
specified first in the command-line when linking.  Not doing so can
result in build failures in certain scenarios.
Ref.: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031450

Adjust linking order of `libmemcached{,util}`

---

.github/workflows/ci.yml

Because [GitHub has deprecated the Ubuntu-18.04 workers](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/), the gearmand CI jobs which run on Ubuntu 18.04 need to be migrated to run in containers instead.

Change CI to test Ubuntu 18.04 in containers

---

.github/workflows/ci.yml

This PR adds a gcc-12 build on Ubuntu 22.04 to the GitHub Actions CI.

Add gcc-12 build to GitHub Actions CI

---

libgearman-server/plugins/base.h
libgearman-server/plugins/queue/sqlite/instance.cc
libgearman-server/plugins/queue/sqlite/queue.cc

if `--store-queue-on-shutdown` is used, database should only be accessed during shutdown and on initial startup. Skipping the done() saves the unnecessary query preparation, database locks, etc...
- fixes #369

skip removing entries from sqlite if store-queue-on-shutdown is used

---

bootstrap.sh

This PR allows bootstrap.sh to run on rocky linux.

add Rocky to supported Linux distributions

---

configure.ac

This PR addresses issue #376 by removing a stray, unbalanced square bracket from the gperf test in `configure.ac`. It also tweaks the error message displayed when gperf is missing to match other similar error messages in `configure.ac`.

Issue #376: Fix configure error when gperf is absent

---

libtest/server.cc

This PR fixes an "issue" reported by the CodeQL scan of the gearmand source code. The null check on [line 179 of libtest/server.cc](https://github.com/gearman/gearmand/blob/8e80a0ded3495496c7037a50eab7fc680c29b2e9/libtest/server.cc#L177-L179) is redundant because it has already been dereferenced on line 177 in the condition of the `for` loop.
I suppose the `if (argv) { ... }` around the `for` loop could also be removed since the new condition of the `for` loop will also test this, but it doesn't do any harm and arguably improves clarity. I'd be willing to remove it though if you think it should be removed, @SpamapS.

Remove "redundant null check due to previous dereference" found in CodeQL scan

---

.github/workflows/codeql.yml

This pull request adds a CodeQL workflow to the repository's GitHub Actions.
See https://codeql.github.com/ for details on CodeQL.
After merging, I think you probably need to enable it in the repository's Settings. See https://docs.github.com/en/code-security/code-scanning/enabling-code-scanning/configuring-default-setup-for-code-scanning for instructions. We need to use the "Advanced" setup because gearmand needs various prerequisites installed.
Some of the warnings seem spurious. You can disable specific warnings on specific lines of the code in the web interface. We'll probably need to do that at some point, but some of the warnings should be fixed, I feel.

Add CodeQL workflow to GitHub Actions

---

.github/workflows/codeql.yml

Sorry, a stray hyphen sneaked in, making the `codeql.yml` syntax invalid and resulting in the error "every step must define a \`uses\` or \`run\` key." Importantly, what this error really means in this case is that every step should only have a single hyphen. My apologies for not catching this before PR #379 was merged.

Fix syntax error in codeql.yml

---

libgearman-server/connection.cc
libgearman-server/plugins/queue/redis/queue.cc
libgearman-server/text.cc
libgearman-server/thread.cc
libgearman/check.cc

Many of these are just typing problems in debug logs and such. However, more-defined behavior is better than undefined, so we'll center on those. This may change some log lines but that's not really a surface whose behaviors we plan to guarantee.

Fixing basic CodeQL alerts

---

libgearman-server/server.cc

These are mostly just a lack of explicit cast.
The issue with strtoll error handling is not serious, but it was potentially confusing with the wrong function mentioned in comments and the log being very vague.
There were also a few places where we call strlen to get the length which isn't what `%.*s` is for.
This should address all outstanding CodeQL alerts.

Address server CodeQL gripes

---

.github/workflows/docs.yml

This PR adds a GitHub Actions workflow to build and publish docs to GitHub Pages.
No idea if this will work. GitHub Actions are difficult to test before merging. I did test building the docs in a local Docker container, but there are many differences with the GitHub Actions environment.

Add GitHub Actions workflow to build and publish docs to GitHub Pages

---

.github/workflows/docs.yml
README.md

This PR makes the following changes to the GitHub Actions workflow for building and deploying the latest documentation to GitHub Pages:
• It updates `actions/configure-pages` to `v5` to address [GitHub's Node16 deprecation](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). (This was causing a warning message.)
• It removes the superfluous `environment` section from build job. (This was causing a warning message.)
• It adds some explicit concurrency rules that I saw in another repository's workflow that sounded like a good idea.
• It updates `README.me` to add a link to the latest gearmand documentation and makes some other minor tweaks (`http:` -> `https:`, punctuation, grammar).

Update and tweak GitHub Actions workflow for building and deploying docs to GitHub Pages

---

.github/workflows/codeql.yml

This merge request updates the GitHub Actions workflow for doing CodeQL analysis. v2 of the CodeQL workflow recipes has been deprecated, so we needed to update to v3. And the workflow failed last night because it couldn't install some package. I think adding a "apt-get update" before the "apt-get install" should fix that.

Update CodeQL Analysis workflow

---

.github/workflows/ci.yml

This merge request attempts to fix various failures with the CI workflow.
• It adds `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true` to the environment to workaround issues with older Ubuntu versions. See https://github.com/actions/checkout/issues/1590 for details. This change fixed the older Ubuntu builds in the Docker images. Alas, this is only a temporary fix, supposedly. Not sure what we are going to do when it no longer works.
• It adds the `ppa:ubuntu-toolchain-r/test` toolchain repository for the gcc-11 build. This fixes the "Unable to locate package gcc-11" error that build was experiencing. Refer to the discussion at https://github.com/actions/runner-images/issues/9679.
• Finally, it adds gcc-13 build on Ubuntu 24.04 to the testing matrix.

Update GitHub Actions CI workflow

---

.github/workflows/ci.yml
tests/libgearman-1.0/internals.cc

This merge request addresses issue #398.
It fixes the reversed `calloc()` arguments in the internals tests that was revealed by building with gcc 14.1 on Ubuntu 24.04.
It also adds a build using gcc-14 on Ubuntu 24.04 to the GitHub Actions CI workflow.

Issue #398: Fix gcc 14 build failure for reversed calloc args

---

docker/example/supervisord/Dockerfile

Resolves #400
```
$ git log -1 --pretty="%h"
5f1c8887
$ make latest 
Building Docker image gearmand/supervisord:1.0...
docker build  --build-arg version=1.0 -t gearmand/supervisord:1.0 .
[+] Building 1.1s (11/11) FINISHED                                                                                                                                             docker:default
=> [internal] load .dockerignore                                                                                                                                                        0.0s
=> => transferring context: 49B                                                                                                                                                         0.0s
=> [internal] load build definition from …
```

supervisord/Dockerfile: install missed tzdata package

---

docker/example/gearmand/Dockerfile
docker/example/gearmand/Makefile
docker/example/gearmand/gearmand.conf
docker/example/supervisord/Dockerfile

This merge request
• bumps the gearmand version number to the latest released version,
• detabifies the Dockerfiles,
• removes the symbolic links previously added to the gearmand image since the `ln` command doesn't work (and isn't needed) on Ubuntu 24.04, and
• changes the timezone used in the images into a Docker image build argument.

Update Dockerfiles for latest gearmand version and other minor tweaks

---

.github/workflows/ci.yml

This pull request partially addresses issue #354 by adding an Alpine 3.17 build to the GitHub Actions CI. As a bonus, this build uses gcc 12 (currently 12.2.1).

Added Alpine builds to GitHub Actions CI

---

.github/workflows/ci.yml
configure.ac

This merge request addresses issue #407 by modifying `configure.ac` so that it is compatible with autoconf 2.72.

Issue #407: Make bootstrap compatible with autoconf 2.72

---

libgearman-server/plugins/queue/redis/queue.cc

This merge request rectifies a CodeQL gripe with an incorrect return value check for a `sscanf()` call:
https://github.com/gearman/gearmand/security/code-scanning/41
I don't actually use Hiredis, so this change is completely untested. I think it's right though. Does it look correct to you, @SpamapS ?

Fix CodeQL gripe with incorrect return value check for sscanf() call

---

libtest/signal.cc
util/signal.cc

This merge request rectifies the CodeQL gripes concerning the usage of `c_str()` pointers after the lifetime of their associated `std::string` objects.
https://github.com/gearman/gearmand/security/code-scanning/39
https://github.com/gearman/gearmand/security/code-scanning/40

Fix CodeQL gripes with usage of c_str() pointers after the lifetime of their associated std::string objects

---

.github/workflows/docs.yml

This merge request modifies the GitHub Actions workflow for building and deploying the docs to GitHub Pages so that it only runs if the GitHub repository owner is gearman. This should prevent these jobs from running on personal forks of the gearmand repository, where they probably wouldn't work anyway since most people don't have GitHub Pages activated.
I'm tired of getting "Run failed: Build and Deploy Docs" emails from GitHub whenever my personal fork syncs up with the master branch.

Only build and deploy the docs to GitHub Pages if the GitHub repository owner is 'gearman'

---

.github/workflows/ci.yml

This merge request adds an Alpine 3.19 build to the GitHub Actions CI.
A previous attempt at this resulted in a segmentation fault during a test; however, I suspect that might have been fixed by PR #404, so let's try again.

Add Alpine 3.19 build to GitHub Actions CI

---

libgearman-server/log.cc

This merge request addresses CodeQL's gripe about an "[uncontrolled format string](https://github.com/gearman/gearmand/security/code-scanning/47)" alert around line 626 of `libgearman-server/gearmand.cc`. The alert suggests that, if a user sets the `GEARMAND_PORT` environment variable to a string with percent characters in it, for example, it could result in a buffer overflow and/or crash the program. (Refer to meta-issue #406.) ~~This merge request addresses that by limiting the string to at most 5 characters (since 65535 is the maximum port number) and then truncating the string at the first non-digit character.~~
~~I believe this PR also addresses issue #320 with Kubernetes setting `GEARMAND_PORT` to unexpected values by default.~~

Address CodeQL gripe about uncontrolled format string in handling of GEARMAND_PORT

---

.github/workflows/ci.yml

This pull request adds gcc-15 build to CI workflow, temporarily (I hope) comments out builds that no longer work, and switches the CI workflow to use actions/checkout@v4.

Add gcc-15 build to CI workflow (and other CI tweaks) [Issue #418]

---

.github/workflows/docs.yml
docs/source/conf.py.in
docs/source/libgearman.rst
docs/source/libgearman/gearman_return_t.rst
docs/source/libgearman/gearman_string_t.rst
docs/source/libgearman/types.rst

This PR addresses issue #373 by fixing a number of warnings and errors emitted by recent versions of Sphinx when building the HTML documentation for gearmand.
It has been successfully tested with Sphinx 7.2.6 on Ubuntu 24.04 and with Sphinx 1.8.5 on Ubuntu 20.04.

Issue #373: Fix sphinx-build warnings and errors when using new versions of Sphinx

---

README.md

Update the build status badge in README.md from Travis CI to GitHub Actions CI. Also, tweak the release instructions one more time.

Update the build status badge to reflect GitHub Actions CI
