- README
- configure.ac
- docs/source/how_to_report_a_bug.rst
- docs/source/install.rst
- docs/source/libgearman.rst
- support/gearmand.spec.in
this pr aims to replace obsolete launchpad url's
> replace launchpad urls by github

- Makefile.am
- docs/include.am
This file is useful for those who want to build the docs.
Closes #21
> Include docs/Makefile in dist tarball

- libgearman-server/plugins/queue/redis/queue.cc
It's incredible, but the old code had the redis server address hard coded to localhost!
I've also added more debugging information when an error occurs.
> More fixes for the redis queue

- PROTOCOL
- bin/gearadmin.cc
- libgearman-server/text.cc
- tests/cli.cc
> Added "prioritystatus" command to display queued jobs broken down by priority.

- libgearman/client.cc
- tests/protocol.cc
- the second part of the issue #76 
- a type test of gearman_connection_create result
> Client issue 76

- README.md
Fixed typos and punctuation. Revised Contributing section for clarity.
> Revisions to README.md

- gearmand/gearmand.cc
- libgearman-server/config.cc
- libgearman-server/config.h
PR should solve thie issue #105
> Issue 105 keepalive

- libgearman-server/gearmand.cc
related to the issue https://github.com/gearman/gearmand/issues/102
> Skip logging of EMFILE error

- libgearman-server/plugins/queue/redis/queue.cc
> bug fixing redis plugin

- libgearman-server/plugins/queue/libmemcached/queue.cc
PR aims to solve issues:
- #120 
- #121
> bug fixing of libmemcached plugin

- libgearman-server/plugins/queue/redis/queue.cc
> ensure data/priority position in hgetall result

- gearmand/gearmand.cc
> removed printing configuration file content on stderr

- libgearman/connection.cc
PR aims to solve the issue #155. It contains the patch [posted](https://github.com/gearman/gearmand/issues/155#issuecomment-403481427) by @dwest1975.
See [remark](https://github.com/gearman/gearmand/issues/155#issuecomment-420662486) according failed OSX build.
> apply "SIGSEGV in gearman_connection_st::receiving"-patch

- libgearman-server/server.cc
an alternative for PR https://github.com/gearman/gearmand/issues/169
to solve https://github.com/gearman/gearmand/issues/168
> bug fixing gearmand crash on logging worker's exception request

- configure.ac
- m4/ax_debug.m4
PR aims to solve build's failure if debug enabled.
For more information see #176, #177.
> solution for issues 176 and 177

- .travis.yml
- libtest/comparison.hpp
- scripts/travis-linux.sh
The PR aims simplify testing newer compilers with Travis CI.
Related issue #188
> run Travis CI tests with g++-6

- .travis.yml
travis_fold described on http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
> append test-suite.log to Travis CI build log

- docs/source/gearmand/ssl.rst
> Improve documentation for using SSL

- .travis.yml
- libgearman-server/plugins/queue/redis/queue.cc
- libtest/http.cc
- tests/httpd_test.cc
Fix issues #213 and #192. Also related to issue #198.
> Fix gcc 8 build errors

- .travis.yml
- libgearman-server/plugins/queue/redis/queue.cc
- libtest/client.cc
* Add clang-4.0 and clang-5.0 builds to Travis CI.
* Resolve clang compilation errors noted in issue #220.
> Support building with clang

- libtest/client.cc
> use TLS_client_method for newer openssl

- libgearman-server/gearmand_con.cc
I think this is a simple typo or copy/paste error. Do you agree?
> Fix debug output in destroy_gearman_server_job_st()

- libboost/config/workaround.hpp
- libtest/server_container.cc
- m4/bottom.m4
This PR aims to provide preliminary work for #291.
For testing purpose `make` and `make test` have been executed on MacOS  https://github.com/p-alik/gearmand/runs/1066606866?check_suite_focus=true
> Refactoring for sake of macOS build

- libgearman-server/plugins/queue/mysql/queue.cc
Adding option MYSQL_OPT_RECONNECT does not give magic possibility to auto recconnect to mysql in you code.
You need to call mysql_ping that will check in case this option connection and do the job.
> Mysql reconnect issue

- bootstrap.sh
This PR aims to support bootstrapping on [NixOS](https://nixos.org/)
> Add NixOS to supported Linux distributions

- libgearman/add.cc
- libtest/drizzled.cc
- libtest/main.cc
While testing gearmand with newer versions of Ubuntu (20.04 and 22.04) I found a few minor things that needed updating in order to build and test.
> Gcc 8+ and 11 fixes

- m4/ax_boost_base.m4
> add loongarch64 support

- m4/ax_boost_base.m4
> Add riscv64 support

- README.md
This should allow anyone with tag write access to release gearmand.
> Add release instructions to README
